# Generated by Django 4.2 on 2023-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='in_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestate',
            name='is_active_in_lease',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestate',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestate',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='prepared_for_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
